const faker = require("faker");
const { Token } = require("../../src/models");
const { userService } = require("../../src/services");

/** Class representing a user for authentication generated by faker.
 *
 */
class testHelperAuth {
  /**
   * Create a user
   * @param {string} name - The user's first and last name.
   * @param {string} email - The user's email address.
   * @param {string} password - The user's password.
   */
  constructor(name, email, password) {
    this.name = name || faker.name.findName();
    this.email = email || faker.internet.email();
    this.password = password || faker.internet.password(8, true, "[a-zA-Z0-9]");
    this.confirmationToken = null;
  }

  async getConfirmationToken() {
    const user = await userService.getUserByEmail(this.email);
    const tokenDocument = await Token.findOne({
      where: { user_id: user.id, type: "confirmation" },
    });
    return tokenDocument;
  }

  getUser() {
    return {
      ...this,
    };
  }

  getUserLogin() {
    return {
      email: this.email,
      password: this.password,
    };
  }

  getWrongUserLogin() {
    return {
      email: this.email,
      password: faker.internet.password(7),
    };
  }

  registration() {
    return {
      name: this.name,
      email: this.email,
      password: this.password,
    };
  }

  badRegistration() {
    let seed = Math.floor(Math.random() * 3) + 1;
    switch (seed) {
      case 1:
        return {
          name: faker.name.findName(),
        };
      case 2:
        return {
          name: faker.name.findName(),
          email: "Bad,..email.c#",
          password: faker.internet.password(),
        };
      case 3:
        return {
          name: faker.name.findName(),
          email: faker.internet.email(),
          password: faker.internet.password(6),
        };
      default:
        return {
          name: faker.name.findName(),
          email: "Bad,..email.c#",
          password: faker.internet.password(),
        };
    }
  }

  getEmail() {
    return this.email;
  }
}

module.exports = { testHelperAuth };
